#!/bin/bash

php composer update --force
php app/console cache:clear --env=prod
php app/console doctrine:schema:create --env=prod
php app/console assets:install --symlink web
php app/console cache:clear
php app/console assetic:dump
