#!/bin/bash
ENV=${1:-"prod"}

composer install
php app/console cache:clear --env=$ENV
php app/console assets:install --env=$ENV --symlink web
php app/console cache:clear --env=$ENV
php app/console assetic:dump --env=$ENV
